name: Java CI with Maven

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: turf_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4  # Updated to v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4  # Updated to v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Setup Chrome Driver
      uses: nanasess/setup-chromedriver@v2.1.1  # Updated to latest version
      
    - name: Start Chrome Driver
      run: |
        chromedriver --url-base=/wd/hub --port=4444 &
        sleep 5  # Wait for Chrome Driver to start
        
    - name: Wait for PostgreSQL
      run: sleep 10  # Wait for PostgreSQL to be ready
      
    - name: Run unit tests
      run: mvn test -Dtest=**/*Test
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/turf_test
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_PROFILES_ACTIVE: test
        
    - name: Run integration tests
      run: mvn verify -DskipITs=false
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/turf_test
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_PROFILES_ACTIVE: test
        
    - name: Run BDD tests
      run: mvn test -Dtest=RunCucumberTest
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/turf_test
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_PROFILES_ACTIVE: test
        
    - name: Upload test results
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: test-reports
        path: |
          target/surefire-reports/
          target/failsafe-reports/
          target/cucumber-reports/
        retention-days: 30

  security-scan:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4  # Updated to v4
    
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'turf-booking-system'
        path: '.'
        format: 'HTML'
        args: >
          --failOnCVSS 7
          --scan **/*.java
          --scan **/pom.xml
          
    - name: Upload security report
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: security-reports
        path: reports/
        
  # SonarQube analysis (optional - comment out if you don't have SonarQube setup)
  sonarqube:
    runs-on: ubuntu-latest
    needs: test
    if: false  # Disabled by default - set to true when you have SonarQube token
    
    steps:
    - uses: actions/checkout@v4  # Updated to v4
      with:
        fetch-depth: 0
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4  # Updated to v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn clean verify sonar:sonar -Dsonar.projectKey=turf-booking-system

  # Build and package (additional job)
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: turf-booking-app
        path: target/*.jar
        retention-days: 7
